<?php
$title ="RESEARCH PHILOSOPHY";
//SET FONT SIZE HERE //>
$fontSize ="30px";
require 'header2.php';
?>    







<!-- ####################################################################################################### -->

<div class="wrapper row4">
  <div id="container" class="clear">
  
    <!-- ####################################################################################################### -->
    <div id="homepage" class="clear">
    <div class="fl_right">
 
<h1>Research Goals, Philosophy, and Methodology</h1>
<p><span>
The primary goal of my career is to have lasting, positive impact in the areas
of computer systems and computer security.   There is a dire and pervasive
need for computers to be more secure.  My research targets real world problems
and deploys solutions to these problems in practice.   My goal is to
solve problems that make a difference in people's lives.
</span></p>

<!------------------------ COMMENT ----------------------

<h2>What is Impact?</h2>
<p><span>
An important role of the academic computer science community is 
the generation and flow of ideas.  One
researcher proposes a new idea that is built upon by other researchers which
moves the focus of the research community in the given direction.   Thus the
metrics of publications (ideas generated) and citations (their influence on
ideas generated by other researchers) along with derived metrics like H-index
or i10-index present an approximate quantification of <i>academic impact</i>.
</span></p>

<p><span>
However, for some academics (including myself), generating a publication is 
only one goal.  There is a desire to create valuable
ideas that can eventually be put into practical use by industry to solve real
world problems.   These academics put substantial effort
into building software used in practice.  The application of generated research
ideas to solve real world problems approximates <i>practical impact</i>.
</span></p>

<p><span>
A further form of influence that professors wield is that which is passed
along to our students.   This can both be through direct interactions (like
mentoring students or teaching a class) and indirect methods (publishing
a textbook or creating widely used educational materials).   The number of
theses supervised, students taught in classrooms, and impact of educational
materials provides an way to evaluate <i>educational impact</i>.
</span></p>

<p><span>
Time is a finite resource, so one must choose how to 
prioritize one's effort.  My priorities align roughly with my school's goals of 
<A HREF="http://www.poly.edu/about/mission">Invention, Innovation, and Entrepreneurship.</A>
As a result, I roughly allot half of my effort to
practical impact and split the remaining effort evenly across educational and
academic impact.   (In contrast, many academics allot essentially no effort to
practical impact.)   As a result, my research group operates and functions in
a different manner than many academic groups.
</span></p>

<h2>How My Research Group Operates</h2>

<p><span>
A key first step in research is to find a topic to study.   Many 
researchers read and discuss papers to come up with new topics or find new
ideas.   While this is a good model for increasing academic impact, many
academic problems and solutions do not translate well to the real world.
</span></p>

------------------------ COMMENT ---------------------->


<p><span>
My group looks for unaddressed real world problems where a solution created
by our team would be likely to make a tangible difference.
Throughout the process of devising a solution we focus on practical concerns
such as the deployability of solutions and the incentives for adoptors to
do so.   Following this, we work with appropriate partners to deploy
our research into pratice.   From these deployments we learn about new
real world problems and use these to drive these new research projects.
</span></p>

<p><span>
Practical impact often necessitates a deployment and thus takes many man-years
of effort beyond a typical research
project.  Thus, I recruit not only students focused on research to participate
in my research group.   I also recruit students that are interested in industry
positions.   These students get valuable hands-on experience with building
and maintaining software deployed in production.   The end result is that my
research group has a substantial number of participants.   For example, in
April 2016, my research group consisted of two research professors,
three full time developers, one design study specialist, seven PhD students, 
five undergraduates, ten masters students, and one high school student.
</span></p>

<p><span>
Students I work with tend to love and embrace the practicality of their work.
We celebrate and work hard to foster large deployments of software (of which 
we have been fortunate to <A HREF="https://seattle.poly.edu/">have</A> 
<A HREF="https://www.cs.arizona.edu/stork/">some</A> 
<A HREF="http://theupdateframework.com/">success</A>).
We are a group of bright and motivated researchers that (in addition to 
publishing papers) work to produce software that changes 
the world.   If you have a similar passion, I invite you to 
<A HREF="mailto:jcappos@nyu.edu">apply</A> to join us!
</span></p>



        </div>
      <?php

require 'sidebar2.php';
?>

<!-- ####################################################################################################### -->
<div style="position:absolute;" class="wrapper row5">
   <div id="copyright" class="clear">
   
 <?php
require 'footer.php';
?>
